# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1369dee2cc3b3fff982a1d6eae9e1fab5c32814d29f7e3eb2d002a8df4053ec1dd0af483e789c68b90bf2e8c379731341d3974ebc2937e8e5b894449e627b91

test:
  secret_key_base: 19417c6498ea9477a5bae9132549f1b0e2548b649c52f6478ef69c40f034c6540eed191f2559a2ac1553063ab3299d38b7c8b612bac4bf13a63950b0bcabcad5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
